using System;
using System.Threading;
using System.Threading.Tasks;
using PcSentinel.Core.Models;

namespace PcSentinel.Core.Interfaces;

/// <summary>
/// Manages the non-blocking background hardware polling lifecycle and telemetry event dispatch.
/// </summary>
public interface IHardwareMonitorService : IDisposable
{
    /// <summary>
    /// Event triggered whenever a fresh hardware telemetry snapshot is gathered.
    /// Guaranteed to carry non-blocking data.
    /// </summary>
    event EventHandler<HardwareSnapshot>? TelemetryUpdated;

    /// <summary>
    /// Event triggered when deterministic trend observations (thermal spikes, sustained load, throttling) are generated.
    /// </summary>
    event EventHandler<IReadOnlyList<TelemetryObservation>>? ObservationsDetected;

    /// <summary>
    /// Currently active monitoring session identifier.
    /// </summary>
    string? ActiveSessionId { get; set; }

    /// <summary>
    /// Most recent deterministic observations generated by local trend analysis.
    /// </summary>
    IReadOnlyList<TelemetryObservation> LatestObservations { get; }

    /// <summary>
    /// Current polling interval in milliseconds (default 1000ms).
    /// </summary>
    TimeSpan PollingInterval { get; set; }

    /// <summary>
    /// Indicates whether the background monitoring thread is active.
    /// </summary>
    bool IsMonitoring { get; }

    /// <summary>
    /// Most recently acquired telemetry snapshot.
    /// </summary>
    HardwareSnapshot? CurrentSnapshot { get; }

    /// <summary>
    /// Starts asynchronous sensor polling.
    /// </summary>
    Task StartAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Stops polling gracefully.
    /// </summary>
    Task StopAsync();

    /// <summary>
    /// Forces an immediate synchronous sensor refresh without waiting for the timer.
    /// </summary>
    Task<HardwareSnapshot> RefreshNowAsync(CancellationToken cancellationToken = default);
}
